# Java Home for Gradle
org.gradle.java.home=/Library/Java/JavaVirtualMachines/openjdk-21.jdk/Contents/Home

# Kotlin
kotlin.code.style=official

# Gradle Memory
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC

# Compose & Wasm
org.jetbrains.compose.experimental.jsoverlay=true
kotlin.incremental.multiplatform=true
